[project]
name = "spotifytool"
version = "0.1.0"
description = "Spotify and SoundCloud downloader CLI"
dependencies = [
    "typer[all]",
    "yt-dlp",
    "fastapi",
    "uvicorn",
    "scdl"
]

[project.scripts]
spotifytool = "core.cli:app"
spotifytool-server = "core.server:start_server"